in progres
PiotrRynio/CodersCamp2021.Project-2.React pull request #23
Opened 2022-01-14 13:57 UTC by BartoszDombrow

2022-01-14 16:11 UTC, RadekDulisz approved these changes

2022-01-14 16:11 UTC, RadekDulisz commented on frontend/src/components/LeftAside/LeftAside.styled.js
> +  height: calc(100vh - 80px);
Czemu tak zrobiłeś?

2022-01-14 17:48 UTC, PiotrRynio reviewed
Całkiem fajny początek

2022-01-14 17:48 UTC, PiotrRynio commented on frontend/src/components/Navbar/Navbar.js
> +      <NavContainer>
Tych dwóch nie można jakoś połączyć?

2022-01-14 17:48 UTC, PiotrRynio commented on frontend/src/components/LeftAside/LeftAside.js
> +const LeftAside = () => {
raczej `left sidebar`, a nie `left side bar`

2022-01-14 17:48 UTC, PiotrRynio commented on frontend/src/components/Navbar/Navbar.js
> +import { AiFillBell } from 'react-icons/ai';
Jak będziecie robić Ikonki to to najlepiej będzie jak skorzystamy tylko z ikonek z jednego źródła. 
Niestety w 
react-icons
 nie ma ikon z  Material-UI, więc w takiej sytuacji proponuję "Font Awesome" (fa) - jest taką jedną z popularniejszych i często przytaczanych na kursach

2022-01-14 17:49 UTC, PiotrRynio requested changes
Blokuję, bo chciałbym jutro jeszcze odpalić sobie. Jak coś to dorób jeszcze jeśl czegoś brakuje

2022-01-15 16:43 UTC, PiotrRynio commented on frontend/src/index.css
> +  border-spacing: 0;
Co tu się zadziało?

2022-01-15 16:43 UTC, PiotrRynio commented on frontend/src/view/viewApp/App.js
> +      </MainTemplate>
Aktualnie też dobrze, ale zastanawiam się, czy nie lepiej strukturę stworzyć taką jak tutaj.
Twoja struktura też bardzo fajna :)

![image](https://user-images.githubusercontent.com/41823689/149629878-bfd90e9d-a388-47aa-a87c-069c31a40fcc.png)

2022-01-15 16:43 UTC, PiotrRynio commented on frontend/src/index.css
> +  border-spacing: 0;
zerknij  na `createGlobalStyle` w styled-components

2022-01-15 18:21 UTC, PiotrRynio commented on frontend/src/components/RightSide/RightSide.js
> +const RightAside = () => {
```suggestion
const RightSidebar = () => {
```

sidebar !== aside

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside

![image](https://user-images.githubusercontent.com/41823689/149632824-208e6100-3009-4d0d-9c48-9cad9883c0c4.png)


![image](https://user-images.githubusercontent.com/41823689/149632818-5e5a542d-8297-498d-b483-cfb6b160d868.png)

2022-01-16 15:29 UTC, PiotrRynio approved these changes

2022-01-16 16:36 UTC, merged